Repository codextraa/Real_Estate, pull requests merged in 2025-09, with the labels that each got.

#8 Docker config and frontend, backend configs
  .dockerignore
  .github/workflows/dev-checks.yml
  backend/.pylintrc
  backend/Dockerfile
  backend/backend/asgi.py
  backend/backend/settings.py
  backend/backend/urls.py
  backend/backend/wsgi.py
  backend/manage.py
  backend/pyproject.toml
  backend/run.sh
  docker-compose.yml
  frontend/Dockerfile
  frontend/eslint.config.mjs
  frontend/next.config.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/run.sh
  frontend/src/app/favicon.ico
  frontend/src/app/globals.css
  frontend/src/app/layout.js
  frontend/src/app/page.js
  frontend/src/app/page.jsx
  frontend/src/app/page.module.css
  frontend/src/libs/api.js
  frontend/src/libs/apiClient.js
  frontend/src/libs/cookie.js
  frontend/src/libs/session.js
  frontend/src/middleware.js
  frontend/src/route.js
  frontend/src/styles/globals.css
Labels: Configuration, DevOps

#9 Docker config and frontend, backend configs
  .dockerignore
  .gitattributes
  .github/workflows/dev-checks.yml
  .vscode/settings.json
  backend/.gitignore
  backend/.pylintrc
  backend/Dockerfile
  backend/backend/asgi.py
  backend/backend/settings.py
  backend/backend/urls.py
  backend/backend/wsgi.py
  backend/manage.py
  backend/pyproject.toml
  backend/run.sh
  docker-compose.yml
  frontend/.gitignore
  frontend/Dockerfile
  frontend/eslint.config.mjs
  frontend/jsconfig.json
  frontend/next.config.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/run.sh
  frontend/src/app/layout.js
  frontend/src/app/page.jsx
  frontend/src/libs/api.js
  frontend/src/libs/apiClient.js
  frontend/src/libs/cookie.js
  frontend/src/libs/session.js
  frontend/src/middleware.js
  frontend/src/route.js
  frontend/src/styles/globals.css
  redis/Dockerfile
Labels: Configuration, DevOps

#11 Added stage-prod-check workflow
  .github/workflows/stage-prod-checks.yml
Labels: DevOps

#19 homepage fixed
  frontend/src/app/layout.jsx
Labels: Enhancement

#23 Signup and login
  frontend/src/actions/authActions.js
  frontend/src/actions/userActions.js
  frontend/src/libs/api.js
  frontend/src/libs/apiClient.js
  frontend/src/libs/cookie.js
  frontend/src/libs/session.js
  frontend/src/middleware.js
Labels: Bug, Enhancement, Feature

#25 User And Admin Tests
  backend/backend/wsgi.py
  backend/core_db/migrations/0002_property_slug.py
  backend/core_db/models.py
  backend/core_db/signals.py
  backend/core_db/tests/__init__.py
  backend/core_db/tests/test_user_admin.py
  backend/core_db/tests/test_user_model.py
  backend/core_db/validators.py
  backend/requirements.txt
Labels: Enhancement, Feature, Test

#31 Added Serializers for Models and created user action
  backend/auth_api/__init__.py
  backend/auth_api/apps.py
  backend/auth_api/serializers.py
  backend/auth_api/views.py
  backend/core_db/tests/test_property_model.py
  backend/core_db/tests/test_user_admin.py
  backend/core_db/tests/test_user_model.py
  backend/property_api/__init__.py
  backend/property_api/apps.py
  backend/property_api/serializers.py
  backend/property_api/views.py
  frontend/src/actions/authActions.js
  frontend/src/actions/userActions.js
  frontend/src/components/forms/LoginForm.jsx
Labels: Enhancement, Feature
